language: node_js
node_js:
- '8'
before_install:
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
- npm install jsdoc publish-if-needed npm@latest -g
install:
- npm install jsdoc -g
- npm install
script:
- "./ci/build.js"
- "./ci/shim.js"
- "./ci/test.js"
after_success:
- publish-if-needed
env:
  global:
    secure: Xlh+lYs1bbTZNInSPKN4tu3dpcrOcMbAdakHbexbItMX1zc0W+uhnWtzZz+xPxi7z03Wy+cQqNndXbxy7ijF1ymfYnBzdbdnQ4I3Ua1lxu5+54No8wicvX0rJcEare87kgkQUAfKBAT+htEdPY/4KAHcAQlr3/bSQqa4sLznYuBGMPKQs650Y82oXsVVeMWbIJrrDZDseymx2v8U1UXpGwgBL2rhrqfQ/0VJUHiGsV8z3BfzxnywNb45KoH6x7Y4wPUgq+rGBqrfz73DLLd/NtGEfsh4OGWYbZJFLy3vH/dh06hC2hVw6bzPvIFCAd3snvwPHEQTQXu++7gHDikHeIfEsNOJFaOP2RYu43a/tIh2IKOcuT3vAAXDHSJS0zJ5jgZVYPUyxde+UTi3n9EI2lJaIPHa2K3k82mCJtti55lsxMuegm0rvojg4iVtMNxBXO2qhKzdwOP9DQMZ+cprai6Vd3Jv72t2Z8faBW7CEdnTepYIjt7EJ8yKFqLGRLRqze8aFwqy4X3tADi20ir9Wvs0xchoInvVM7J0k8PDPDcuZ/YmVjBBvks6xJgkr7Iuai04vcD2GwkJoPXbxh0ZxgI3deBlWdiavPwz6KgMvckkL1wbIMALgyNup0t0Z0YHVRCv5YuUcjtCZfTvPyfQbPhc0/0lZNFQND60s/3Lzm8=
